name: kuzushiji-yolox

device: cuda
use_amp: false
num_epochs: 100
hidden_channels: 64
root_dir: /store/kuzushiji-recognition
depth: 1
num_classes: 1
feat_range: [4, 6]
box_iou_threshold: 0.5
score_threshold: 0.5
image_size: 512

assign:
  topk: 10
  radius: 2.0
  center_weight: 0.5
  obj_weight: 1.0
  box_weight: 1.5

optimizer:
  lr: 5e-3

criterion:
  box_weight: 0.5
  cls_weight: 0.0

train_loader:
  batch_size: 8
  shuffle: true
  num_workers: 6
  drop_last: true

val_loader:
  batch_size: 8
  shuffle: false
  num_workers: 6

fold:
  n_splits: 5
  fold_idx: 1
