topk: 10
config_paths:
  - config/v2-4.fine.yaml # LOCAL: 0.9889  PUBLIC:
  # - config/v2.1-0.yaml # LOCAL: 0.9956 PUBLIC: 0.9136
  # - config/v2-0.yaml # LOCAL: 0.9868 PUBLIC: 0.9727
  # - config/v2-1.yaml # LOCAL:0.9934  PUBLIC: 0.9439
  # - config/v2-1.fine.yaml # LOCAL:  PUBLIC:
  # - config/v2-2.yaml # LOCAL:0.9956  PUBLIC: 0.9405
  # - config/v2-2.fine.yaml # LOCAL:0.9956  PUBLIC: 0.9433014
  # - config/v2-3.yaml # LOCAL:0.9933  PUBLIC:
