topk: 10
config_paths:
  # - config/v2-4.fine.yaml # LOCAL: 0.9889  PUBLIC:
  # - config/v2.1-0.yaml # LOCAL: 0.9956 PUBLIC: 0.9136
  # - config/v2-0.yaml # LOCAL: 0.9868 PUBLIC: 0.9727
  # - config/v2-1.yaml # LOCAL:0.9934  PUBLIC: 0.9439
  # - config/v2-1.fine.yaml # LOCAL:  PUBLIC:
  # - config/v2-2.yaml # LOCAL:0.9956  PUBLIC: 0.9405
  # - config/v2-2.fine.yaml # LOCAL:0.9956  PUBLIC: 0.9433014
  # - config/v2-3.yaml # LOCAL:0.9933  PUBLIC:
  # - config/v3-0.fine.yaml # LOCAL:0.9649  PUBLIC: 0.4382819
  # - config/v3-0.flip.yaml # LOCAL:0.9868  PUBLIC: 0.9520649
  # - config/v4-0.yaml # LOCAL:0.990  PUBLIC: 0.9443215
  # - config/v5-base-0.yaml # LOCAL:0.9868  PUBLIC: 0.9727 copy model of v2-0
  # - config/v5-fine-0.yaml # LOCAL:-  PUBLIC: 0.9700274 etrain of v5-base-0
  - config/v5-fine-1.yaml # LOCAL:0.9868  PUBLIC: check old config
