name: v2
seed: 1024
fold: 4
kfold: 5
batch_size: 16
model_name: tf_efficientnet_b4_ns
lr: 0.000015564766155184
image_size: 512
embedding_size: 1024
arcface_scale: 15.18386107223457
arcface_margin: 8.713547214550443
brightness_limit: 0.0
contrast_limit: 0.0
hue_shift_limit: 0.0
sat_shift_limit: 0.0
val_shift_limit: 0.0
scale_limit: 0.0
sub_centers: 4
rotate_limit: 0.0
warmup_t: 1
epochs: 67
patience: 20
num_model_nos: 244
n_neighbors: 94
vflip_p: 0.0
hflip_p: 0.0
random_rotate_p: 0.0
loss_type: "ArcFaceLoss"
is_fine: true
previous:
  is_fine: false
registry_augmentations:
  - rot90
  - rot180
  - rot270
  - rot30
