name: v3-no-aug
seed: 1024
fold: 0
kfold: 5
batch_size: 16
model_name: tf_efficientnet_b5_ns
lr: 0.0000585564766155184
image_size: 380
embedding_size: 1024
arcface_scale:  22.963525331959204
arcface_margin: 13.16048938567629
brightness_limit: 0.0
contrast_limit: 0.0
hue_shift_limit: 0.0
sat_shift_limit: 0.0
val_shift_limit: 0.0
scale_limit: 0.0
sub_centers: 4
rotate_limit: 0.0
warmup_t: 1
epochs: 57
patience: 11
num_model_nos: 244
n_neighbors: 94
random_rotate_p: 1.0
vflip_p: 0.0
hflip_p: 0.0
loss_type: "ArcFaceLoss"
is_fine: true
train_with_flipped: true
use_scheduler: false

previous:
  is_fine: false
  name: v3
### memo
# LOCAL: 0.9612
