name: v5-fine-3
seed: 1024
fold: 0
kfold: 5
batch_size: 16
model_name: tf_efficientnet_b4_ns
lr: 0.000015564766155184
image_size: 576
embedding_size: 1024
arcface_scale: 22.964
arcface_margin: 7.739
brightness_limit: 0.391
contrast_limit: 0.291
hue_shift_limit: 0.28
sat_shift_limit: 0.225
val_shift_limit: 0.28
scale_limit: 0.18529016025844874
sub_centers: 4
rotate_limit: 32.394467397006466
accumulate_grad_batches: 2
max_epochs: 30
warmup_t: 1
epochs: 57
patience: 11
num_model_nos: 244
n_neighbors: 376
vflip_p: 0.0
hflip_p: 0.0
random_rotate_p: 0.5
use_scheduler: false
loss_type: "ArcFaceLoss"
train_with_flipped: true
registry_rot_augmentations:
  - 90
  - 180
  - 270

hard_samples:
  - '031/7.jpg'
previous:
  name: v5-base
  image_size: 512
