version: '2.4'

x-env: &env
  TENSORBOARD_PORT: ${TENSORBOARD_PORT:?}
  CODECOV_TOKEN: &CODECOV_TOKEN ${CODECOV_TOKEN}
  KAGGLE_USERNAME: &KAGGLE_USERNAME ${KAGGLE_USERNAME}
  KAGGLE_KEY: &KAGGLE_KEY ${KAGGLE_KEY}


x-app: &app
  shm_size: '30gb'
  image: "vision-tools-dev"

  build:
    context: .
  volumes:
    - .:/app
    - ./signate.json:/root/.signate/signate.json
    - ./store:/store
    - ./.cache:/root/.cache

    - ./store/tensorflow-great-barrier-reef:/kaggle/input/tensorflow-great-barrier-reef
    - ./:/kaggle/input/packages/vision-tools/
    - ./cots_bench/runs:/runs/cots
    - ./kuzushiji_bench/runs:/runs/kuzushiji
    - ./hwad_bench/pipeline/runs:/runs/hwad_bench



services:
  app:
    <<: *app
    environment:
      KAGGLE_USERNAME: *KAGGLE_USERNAME
      KAGGLE_KEY: *KAGGLE_KEY
      CODECOV_TOKEN: *CODECOV_TOKEN
      CONFIG_FILE:

  tensorboard:
    <<: *app
    command: tensorboard --logdir=${TENSORBOARD_RUNS:?} --host=0.0.0.0 --port=${TENSORBOARD_PORT}
    ports:
      - "${TENSORBOARD_PORT}:${TENSORBOARD_PORT}"
