version: '2.4'

x-env: &env
  TENSORBOARD_PORT: ${TENSORBOARD_PORT:?}
  NOTEBOOK_PORT: ${NOTEBOOK_PORT:?}
  CODECOV_TOKEN: &CODECOV_TOKEN ${CODECOV_TOKEN}
  KAGGLE_USERNAME: &KAGGLE_USERNAME ${KAGGLE_USERNAME}
  KAGGLE_KEY: &KAGGLE_KEY ${KAGGLE_KEY}
  STORE_DIR: &STORE_DIR ${STORE_DIR}


x-app: &app
  shm_size: '30gb'
  image: "vision-tools-dev"

  build:
    context: .
  volumes:
    - .:/app
    - ./signate.json:/root/.signate/signate.json
    - $STORE_DIR:/store
    - ./.cache:/root/.cache


services:
  app:
    <<: *app
    environment:
      KAGGLE_USERNAME: *KAGGLE_USERNAME
      KAGGLE_KEY: *KAGGLE_KEY
      CODECOV_TOKEN: *CODECOV_TOKEN
      CONFIG_FILE:
      NVIDIA_VISIBLE_DEVICES:

  tensorboard:
    <<: *app
    command: tensorboard --logdir=${TENSORBOARD_RUNS:?} --host=0.0.0.0 --port=${TENSORBOARD_PORT}
    ports:
      - "${TENSORBOARD_PORT}:${TENSORBOARD_PORT}"

  notebook:
    <<: *app
    command: jupyter notebook --ip 0.0.0.0 --port ${NOTEBOOK_PORT} --allow-root --NotebookApp.password='' --NotebookApp.token=''
    ports:
      - "${NOTEBOOK_PORT}:${NOTEBOOK_PORT}"
