version: '2.4'

x-env: &env
  TENSORBOARD_PORT: ${TENSORBOARD_PORT:?}
  CODECOV_TOKEN: &CODECOV_TOKEN ${CODECOV_TOKEN}
  KAGGLE_USERNAME: &KAGGLE_USERNAME ${KAGGLE_USERNAME}
  KAGGLE_KEY: &KAGGLE_KEY ${KAGGLE_KEY}
  

x-app: &app
  shm_size: '30gb'
  image: "vision-tools-dev"

  build: 
    context: .
  volumes:
    - .:/app
    - ./store:/store
    - ./.cache:/root/.cache


services:
  app:
    <<: *app
    environment:
      KAGGLE_USERNAME: *KAGGLE_USERNAME
      KAGGLE_KEY: *KAGGLE_KEY
      CODECOV_TOKEN: *CODECOV_TOKEN

  tensorboard:
    <<: *app
    command: tensorboard --logdir=runs --host 0.0.0.0 --port=${TENSORBOARD_PORT}
    ports:
      - "${TENSORBOARD_PORT}:${TENSORBOARD_PORT}"


