name: convnext_small
embedding_size: 512
pretrained: true
version: v2
fold: 0

use_amp: true
epochs: 999
batch_size: 16
eval_interval: 1000
resume: best_score
min_samples: 4
lr: 1.0e-4
weight_decay: 0.05
steps_per_epoch: 100
lr_patience: 2
lr_factor: 0.9
total_steps: 50_000
warmup_steps: 5_000
num_classes: 15587

image_width: 512
image_height: 512

affine_p: 1.0
rot0: 0
rot1: 0
shear0: -10
shear1: 10
trans0: 0.0
trans1: 0.0

brightness: 0.1
contrast: 0.2
saturation: 0.2
hue: 0.01
color_jitter_p: 1.0
to_gray_p: 0.0
hflip_p: 0.5
