# device
device: cuda:0
num_workers: 8
# data
train_annotation_path: /app/hwad_bench/store/train.csv

# model
name: convnext_small
fold: 0
version: v4

embedding_size: 512
pretrained: true

use_amp: true
epochs: 999
batch_size: 16
eval_interval: 2000
resume: latest
min_samples: 0
lr: 1.5e-4
weight_decay: 0.05
lr_patience: 2
lr_factor: 0.9
total_steps: 80_000
warmup_steps: 4_000
accumulate_steps: 1
num_classes: 15587

image_width: 512
image_height: 512

affine_p: 1.0
rot0: 0
rot1: 0
shear0: -10
shear1: 10
trans0: -0.1
trans1: 0.1
scale0: 0.6
scale1: 1.4

brightness: 0.1
contrast: 0.2
saturation: 0.2
hue: 0.01
color_jitter_p: 1.0
to_gray_p: 0.1
hflip_p: 0.5
