# device
device: cuda:1
num_workers: 6
# data
train_annotation_path: /app/hwad_bench/store/train.csv

# model
name: tf_efficientnet_b5_ns
fold: 0
version: v5

embedding_size: 512
pretrained: true

use_amp: true
epochs: 999
batch_size: 16
eval_interval: 1000
resume: latest
min_samples: 4
lr: 1.0e-4
weight_decay: 0.05
lr_patience: 2
lr_factor: 0.9
total_steps: 120_000
warmup_steps: 4_000
accumulate_steps: 8
num_classes: 15587

image_width: 640
image_height: 640

affine_p: 1.0
rot0: 0
rot1: 0
shear0: -10
shear1: 10
trans0: -0.1
trans1: 0.1
scale0: 0.6
scale1: 1.4

brightness_limit: 0.1
contrast_limit: 0.1
sat_shift_limit: 10
hue_shift_limit: 5
val_shift_limit: 10
to_gray_p: 0.1
hflip_p: 0.5
