# device
device: cuda:0
num_workers: 6
# data
train_annotation_path: /app/hwad_bench/store/train.csv

# model
name: tf_efficientnet_b5_ns
fold: 0
version: v11

embedding_size: 512
pretrained: true

use_amp: true
epochs: 999
batch_size: 8
eval_interval: 5000
use_scheduler: false
resume: best_score
min_samples: 4
lr: 5.0e-5
final_div_factor: 100
weight_decay: 0.05
lr_patience: 2
lr_factor: 0.9
total_steps: 200_000
warmup_steps: 4_000
accumulate_steps: 16
num_classes: 15587

image_width: 640
image_height: 640

affine_p: 1.0
rot0: 0
rot1: 0
shear0: -5
shear1: 5
trans0: -0.125
trans1: 0.125
scale0: 0.75
scale1: 1.25

brightness_limit: 0.3
contrast_limit: 0.01
sat_shift_limit: 10
hue_shift_limit: 5
val_shift_limit: 10
to_gray_p: 0.1
hflip_p: 0.5
