use_amp: true
epochs: 999
batch_size: 16
num_workers: 6
eval_interval: 1000
resume: best_score
min_samples: 0
lr: 1.0e-4
weight_decay: 0.05
steps_per_epoch: 100
warmup_steps: 10_000
total_steps: 100_000
num_classes: 15587

affine_p: 0.9
image_width: 512
image_height: 512
hue_p: 0.9
random_resized_crop_p: 1.0
hflip_p: 0.5
