name: v3
seed: 1024
fold: 0
kfold: 4
batch_size: 8
model_name: tf_efficientnet_b4_ns
lr: 0.000685564766155184
image_size: 480
embedding_size: 1024
arcface_scale: 22.195484048785843
arcface_margin: 9.287880774585709
brightness_limit: 0.00
contrast_limit: 0.000
hue_shift_limit: 0.00
sat_shift_limit: 0.00
val_shift_limit: 0.00
scale_limit: 0.18529016025844874
sub_centers: 8
rotate_limit: 32.394467397006466
warmup_t: 1
epochs: 57
patience: 11
n_neighbors: 200
blur_p: 0.4
vflip_p: 0.0
hflip_p: 0.0
loss_type: "ArcFaceLoss"

hard_samples:
  - '031/7.jpg'
  - '049/7.jpg'
  - '002/4.jpg'

fine:
  lr: 0.0001
  checkpoint_dir: 'fine-checkpoints'
  scale_limit: 0.0
  rotate_limit: 0.0
