name: v2s-1024
image_size: 1024
seed: 42
n_splits: 5
valid_epochs: 1
batch_size: 13
model_name: "tf_efficientnetv2_s"
lr: 0.0005094480973201417
accumulation_steps: 2
ratio: 0.275
optimizer: "AdamW"
drop_rate: 0.3
drop_path_rate: 0.2
weight_decay: 1.0e-6
affine_scale: 0.2
affine_translate: 0.01
vflip_p: 0.5
affine_p: 0.5
use_roi: false
data_path: /app/store
threshold: 0.74
