name: 512-drop-search
image_size: 512
seed: 42
n_splits: 5
valid_epochs: 1
batch_size: 16
model_name: "tf_efficientnet_b4_ns"
lr: 0.00098
accumulation_steps: 1
ratio: 0.275
use_roi: false
affine_p: 0.17
vflip_p: 0.5

search_config:
  drop_rate_range: [0.0, 0.5]
  drop_path_rate_range: [0.0, 0.5]
  weight_decay_range: [1.0e-6, 1.0e-2]
