image_size: 1536
seed: 42
n_splits: 5
batch_size: 7
model_name: "tf_efficientnet_b2_ns"
lr: 0.0001094480973201417
ratio: 0.5
validation_steps: 100
accumulation_steps: 3
drop_rate: 0.391
drop_path_rate: 0.13
num_workers: 6
affine_p: 0.1
use_scheduler: false
use_roi: true

previous_name: b2-1536-roi-f0-0
