name: trial-1
image_size: 1024
seed: 42
n_splits: 5
valid_epochs: 1
batch_size: 15
model_name: "tf_efficientnet_b2_ns"
lr: 0.0005094480973201417
ratio: 0.5369031081273525
accumulation_steps: 2
epochs: 20

threshold: 0.69
use_roi: true
