name: trial-b3-0.fine-0
image_size: 1024
seed: 42
n_splits: 5
batch_size: 10
model_name: "tf_efficientnet_b3_ns"
lr: 0.0001094480973201417
use_scheduler: false
ratio: 0.5369031081273525
accumulation_steps: 2
validation_steps: 100
threshold: 0.87

previous_name: trial-b3-0.fine
