name: trial-b3-roi-vflip
image_size: 1024
seed: 42
n_splits: 5
valid_epochs: 1
batch_size: 10
model_name: "tf_efficientnet_b3_ns"
lr: 0.0005094480973201417
ratio: 0.5369031081273525
accumulation_steps: 2
epochs: 20
use_roi: true
