name: trial-b2-roi-acc1
image_size: 1024
seed: 42
n_splits: 5
valid_epochs: 1
batch_size: 15
model_name: "tf_efficientnet_b2_ns"
lr: 0.0009094480973201417
ratio: 0.5369031081273525
accumulation_steps: 1
epochs: 20
vflip_p: 0.5


threshold: 0.61
use_roi: true
