name: yolox

device: cuda
use_amp: false
epochs: 999
hidden_channels: 128
dataset_dir: /kaggle/input/tensorflow-great-barrier-reef
store_dir: /kaggle/input/packages/vision-tools/cots_bench/store
depth: 1
num_classes: 1
feat_range: [3, 5]
original_width: 1280
original_height: 720

resume_target: current

backbone_type: efficientnet
backbone_name: efficientnet-b3
val_iou_thresholds: [0.4]

to_boxes:
  iou_threshold: 0.5
  conf_threshold: 0.5
  limit: 1000


assign:
  topk: 9
  radius: 2.5
  box_weight: 3.0

lr: 1.0e-3
fine_lr: 1.0e-4

  # momentum: 0.95
  # nesterov: false

criterion:
  box_weight: 0.2
  cls_weight: 0.0

train_loader:
  batch_size: 5
  shuffle: true
  num_workers: 6
  drop_last: false

val_loader:
  batch_size: 5
  shuffle: false
  num_workers: 6

n_splits: 5
fold: 0
