name: yolox

device: cuda
use_amp: true
epochs: 999
hidden_channels: 32
dataset_dir: /kaggle/input/tensorflow-great-barrier-reef
store_dir: /kaggle/input/packages/vision-tools/cots_bench/store
depth: 1
num_classes: 1
feat_start: 3
feat_end: 6
head_start: 1
head_end: 2

image_width: 1920
image_height: 1280

original_width: 1280
original_height: 720

resume_target: checkpoint

backbone_type: efficientnet
backbone_name: efficientnet-b3
iou_thresholds:
  - 0.30
  - 0.35
  - 0.40
  - 0.45
  - 0.50
  - 0.55
  - 0.60
  - 0.65
  - 0.70
  - 0.75
  - 0.80

val_iou_thresholds: [0.3]


cut_and_paste_p: 0.9
cut_and_paste_scale_min: 0.5
cut_and_paste_scale_max: 1.1
cut_and_paste_radius: 0.3

## rough
mosaic_p: 0.9
hue_p: 0.9
eval_interval: 50
lr: 5.0e-4

## fine
# mosaic_p: 0.0
# hue_p: 0.0
# eval_interval: 1
# lr: 1.0e-5

to_boxes:
  iou_threshold: 0.4
  conf_threshold: 0.55
  limit: 2000

assign:
  topk: 9
  radius: 3
  box_weight: 3.0


criterion:
  box_weight: 0.3
  cls_weight: 0.0

train_loader:
  batch_size: 5
  shuffle: true
  num_workers: 5
  drop_last: true

val_loader:
  batch_size: 9
  num_workers: 5

n_splits: 5
fold: 1
