name: yolox

device: cuda
use_amp: true
epochs: 999
hidden_channels: 72
dataset_dir: /kaggle/input/tensorflow-great-barrier-reef
store_dir: /kaggle/input/packages/vision-tools/cots_bench/store
depth: 1
num_classes: 1
fpn_start: 3
fpn_end: 5

image_width: 2560
image_height: 1440

original_width: 1280
original_height: 720

resume_target: current
# resume_target: checkpoint

backbone_type: efficientnet
backbone_name: efficientnet-b3
val_iou_thresholds: [0.4]
lookahead_k: 5
lookahead_alpha: 0.5

to_boxes:
  iou_threshold: 0.4
  conf_threshold: 0.01
  limit: 1000

assign:
  topk: 9
  radius: 2.5
  box_weight: 3.0

lr: 1.0e-3
fine_lr: 1.0e-4

  # momentum: 0.95
  # nesterov: false

criterion:
  box_weight: 0.2
  cls_weight: 0.0

train_loader:
  batch_size: 5
  shuffle: true
  num_workers: 6
  drop_last: false

val_loader:
  batch_size: 4
  num_workers: 6

n_splits: 5
fold: 0
