name: yolox

device: cuda
use_amp: true
epochs: 999
hidden_channels: 48
dataset_dir: /kaggle/input/tensorflow-great-barrier-reef
store_dir: /kaggle/input/packages/vision-tools/cots_bench/store
depth: 1
num_classes: 1
fpn_start: 2
fpn_end: 5

image_width: 1280
image_height: 720

original_width: 1280
original_height: 720

resume_target: current
# resume_target: checkpoint

backbone_type: efficientnet
backbone_name: efficientnet-b2

val_iou_thresholds: [0.3]
lookahead_k: 5
lookahead_alpha: 0.5
mosaic_p: 0.7

to_boxes:
  iou_threshold: 0.4
  conf_threshold: 0.5
  limit: 2000

assign:
  topk: 9
  radius: 2.5
  box_weight: 3.0

lr: 1.0e-3
fine_lr: 1.0e-4

criterion:
  box_weight: 0.5
  cls_weight: 0.0

train_loader:
  batch_size: 11
  shuffle: true
  num_workers: 6
  drop_last: true

val_loader:
  batch_size: 11
  num_workers: 6

n_splits: 5
fold: 0
