name: yolox

device: cuda
use_amp: true
epochs: 999
hidden_channels: 48
dataset_dir: /kaggle/input/tensorflow-great-barrier-reef
store_dir: /kaggle/input/packages/vision-tools/cots_bench/store
depth: 1
num_classes: 1
fpn_start: 3
fpn_end: 5

image_width: 1792
image_height: 1024

original_width: 1280
original_height: 720

resume_target: checkpoint

backbone_type: efficientnet
backbone_name: efficientnet-b2
iou_thresholds:
  - 0.30
  - 0.35
  - 0.40
  - 0.45
  - 0.50
  - 0.55
  - 0.60
  - 0.65
  - 0.70
  - 0.75
  - 0.80
  - 0.85

val_iou_thresholds: [0.3]
lookahead_k: 5
lookahead_alpha: 0.5
mosaic_p: 0.4

to_boxes:
  iou_threshold: 0.4
  conf_threshold: 0.3
  limit: 2000

assign:
  topk: 9
  radius: 1.5
  box_weight: 3.0

lr: 1.0e-3
fine_lr: 1.0e-4

criterion:
  box_weight: 0.5
  cls_weight: 0.0

train_loader:
  batch_size: 6
  shuffle: true
  num_workers: 5
  drop_last: true

val_loader:
  batch_size: 6
  num_workers: 5

n_splits: 5
fold: 0
